### ISSUE TITLE
PreCompiled files are out of date

### ISSUE THREAD

**Issue by MarkGoldberg** [djeedjay/DebugViewPP#273]
The wordpress site has version 1.2
The readme mentions a September version, but the exe is from March - both are 1.5.x
The readme mentions a 1.7, but there are no pre-compiled versions to download

**Comment by janwilmans** [comment]
Hi Mark, thanks for your email, please check out the releases on 
https://github.com/djeedjay/DebugViewPP/releases
The wordpress site is not maintained by me, so I cannot do much about it.

**Comment by janwilmans** [comment]
I (hopefully) marked the download link more clearly:
![image](https://user-images.githubusercontent.com/5933444/27217606-e2f0ecd4-527a-11e7-8c77-0a4c766e947d.png)

**Comment by MarkGoldberg** [comment]
Hi Jan,

Thank you again, for another quick response.
I'm replying by eMail as you closed the issue.
You added to the readme.md
+[Download latest here](https://github.com/djeedjay/DebugViewPP/releases/
tag/v1.8-alpha)

It might be better to simply link to (https://github.com/djeedjay/
DebugViewPP/releases)
for two reasons
1) it shows more information
2) it's a permanent link, no need to maintain the readme.md as for each new
tag


Mark Goldberg


Completely unrelated issue:
    do you know why V1.7.0.35 takes 40 seconds to load (from launch to
first responsiveness)
    I jumped from a version 1.5, and that took just a couple of seconds to
load.

**Comment by janwilmans** [comment]
Actually, you are not replying by email :) in the sense that this conversation is still published on github (there is essentially no difference to adding a comment online, or replying to the email notification.) You can also still comment on closed issues online.

The hard-link in the readme.md was intentional, because I want to direct people to the 'recommended' download. People apparently has trouble finding the 'Releases' Tab. :)  I get asked a lot 'what version should I download', so I will maintain it manually. 

you can contact me directly at janwilmans@gmail.com, I think the 40 seconds startup time is weird...
I do not see it, it starts in an instant here (not seconds, just instantly)

**Comment by MarkGoldberg** [comment]
Jan spent a fair bit of effort with me via email
He had me create a video using jing to show him what I was seeing

He noticed that I had 10 tabs open, and he suggested that I save them and close them
actually he suggested that I delete the registry entries where they are persisted
HKEY_CURRENT_USER\Software\Cobalt Fusion\DebugView++

I was able to the solve the problem just using the user interface of DebugView++
   I saved and closed all of my tabs
   that alone fixed the problem
   what's interesting is I was able to re-add and restore those same 10 tabs
   and DebugView++ 1.7.x (32 and 64 bit) both launch instantly

**Thank you again Jan for your excellent and quick support**
